version: "3.1"
services:
  frontend:
    # TODO: foloseste imaginea de pe dockerhub
    image: avatario_frontend_test:latest
    depends_on:
      - database
      - backend-api
      - backend-data
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "80:80"
    networks:
      - webnetwork
    stdin_open: true
  backend-api:
    image: rosudavidg/avatario-backend-api:latest
    ports:
      - "5000:5000"
    networks:
      - webnetwork
    volumes:
      - ./backend-api:/usr/src/app/
    environment:
      BACKEND_DATA_HOST: backend-data
      BACKEND_DATA_PORT: 5000
      DATABASE_USER: /run/secrets/secret_database_user
      DATABASE_HOST: database
      DATABASE_PASSWORD: /run/secrets/secret_database_password
      DATABASE_NAME: /run/secrets/secret_database_db
      DATABASE_PORT: 5432
      JWT_ISSUER: avatario_backend_api
      JWT_SUBJECT: Authentication token
      JWT_AUDIENCE: avatario_frontend
      JWT_EXPIRESIN: 1w
      JWT_SECRET_KEY: /run/secrets/secret_jwt_key
    secrets:
      - secret_database_user
      - secret_database_password
      - secret_database_db
      - secret_jwt_key
  backend-data:
    deploy:
      placement:
        constraints:
          - "node.role==manager"
    image: rosudavidg/avatario-backend-data:latest
    depends_on:
      - "database"
    volumes:
      - ./backend-data:/usr/src/app/
      - volume_backend_data:/images
    networks:
      - webnetwork
    environment:
      DATABASE_USER: /run/secrets/secret_database_user
      DATABASE_PASSWORD: /run/secrets/secret_database_password
      DATABASE_DB: /run/secrets/secret_database_db
    secrets:
      - secret_database_user
      - secret_database_password
      - secret_database_db
  database:
    deploy:
      placement:
        constraints:
          - "node.role==manager"
    image: rosudavidg/avatario-database:latest
    environment:
      POSTGRES_USER_FILE: /run/secrets/secret_database_user
      POSTGRES_PASSWORD_FILE: /run/secrets/secret_database_password
      POSTGRES_DB_FILE: /run/secrets/secret_database_db
    secrets:
      - secret_database_user
      - secret_database_password
      - secret_database_db
    volumes:
      - volume_database:/var/lib/postgresql/data
    ports:
      - "54321:5432"
    networks:
      - webnetwork
networks:
  webnetwork:
volumes:
  volume_backend_data:
  volume_database:
secrets:
  secret_database_password:
    file: ./secrets/secret_database_password
  secret_database_user:
    file: ./secrets/secret_database_user
  secret_database_db:
    file: ./secrets/secret_database_db
  secret_jwt_key:
    file: ./secrets/secret_jwt_key
