version: "3.1"
services:
  backend-api:
    depends_on:
      - database
      - backend-data
    build:
      dockerfile: Dockerfile
      context: ./backend-api
    ports:
      - "8888:5000"
    networks:
      - webnetwork
    volumes:
      - ./backend-api:/usr/src/app/
  backend-data:
    depends_on:
      - database
    build:
      dockerfile: Dockerfile
      context: ./backend-data
    ports:
      - "5000:5000"
    volumes:
      - ./backend-data:/usr/src/app/
      - volume_backend_data:/images
    networks:
      - webnetwork
    environment:
      DATABASE_USER: /run/secrets/secret_database_user
      DATABASE_PASSWORD: /run/secrets/secret_database_password
      DATABASE_DB: /run/secrets/secret_database_db
    secrets:
      - secret_database_user
      - secret_database_password
      - secret_database_db
  database:
    build:
      dockerfile: Dockerfile
      context: ./database
    environment:
      POSTGRES_USER_FILE: /run/secrets/secret_database_user
      POSTGRES_PASSWORD_FILE: /run/secrets/secret_database_password
      POSTGRES_DB_FILE: /run/secrets/secret_database_db
    secrets:
      - secret_database_user
      - secret_database_password
      - secret_database_db
    ports:
      - "54321:5432"
    networks:
      - webnetwork
networks:
  webnetwork:
volumes:
  volume_backend_data:
secrets:
  secret_database_password:
    file: ./secrets/secret_database_password
  secret_database_user:
    file: ./secrets/secret_database_user
  secret_database_db:
    file: ./secrets/secret_database_db
